sudo: required

language: python
python:
  - 3.6

services:
  - docker
  - memcached

os:
  - linux

env:
  global:
    - RELEASE_NAME="myuw"
    - DJANGO_APP="myuw"
    - COMMIT_HASH="$(git rev-parse --short=7 HEAD)"
    - IMAGE_TAG="${RELEASE_NAME}:${COMMIT_HASH}"
    - DEPLOY_SCRIPT_BASE=https://raw.githubusercontent.com/uw-it-aca/gcp-app-deploy/master

install:
  - docker build --target myuw -t "$IMAGE_TAG" .
  - docker build -t "${IMAGE_TAG}-test" .

before_script:
  - gem install coveralls-lcov
  - pip install coverage
  - pip install coveralls

script:
  - docker run -u root -it -v /tmp:/coverage -e DJANGO_APP="$DJANGO_APP" -e "ENV=localdev" -e "AUTH=SAML_MOCK" -e "MEMCACHED_SERVER_COUNT=1" -e "MEMCACHED_SERVER_SPEC=localhost" "${IMAGE_TAG}-test" bash -c ". ./travis-ci/test.sh"

after_success:
  - cp /tmp/.coverage.* /tmp/lcov.info .
  - coverage combine
  - coveralls-lcov -v -n lcov.info > js-coverage.json
  - coveralls --merge=js-coverage.json
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      case "$TRAVIS_BRANCH" in
        "master")
          export APP_INSTANCE="prod";
          ;;
        "develop")
          export APP_INSTANCE="test";
          ;;
        "qa")
          export APP_INSTANCE="qa";
          ;;
        "feature/gcp")
          export APP_INSTANCE="dev";
          ;;
        *)
          unset APP_INSTANCE
          ;;
      esac
      if [[ "$APP_INSTANCE" ]]; then
        curl -Ls ${DEPLOY_SCRIPT_BASE}/travis-ci/deploy.sh | bash;
      fi
    fi

cache:
  directories:
    - "$HOME/helm"
    - "$HOME/kubeval"
