version: '3.4'

services:
  myuw:
    build:
      context: .
      target: app-container
    container_name: app-myuw
    volumes:
      - ./myuw:/app/myuw
    ports:
      - "8000:8000"
    environment:
      ENV: localdev
      AUTH: SAML_MOCK
      PORT: ${PORT:-8000}
      COMPRESSOR_ENABLED: "False"
    stdin_open: true
    tty: true
