version: '3.4'

services:
  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    volumes:
      - ./myuw:/e2e/myuw
      - ./cypress:/e2e/cypress
    stdin_open: true
    tty: true
