version: '3.4'

services:
  myuw:
    build: .
    container_name: app-myuw
    volumes:
      - ./myuw:/app/myuw
      - statics-volume:/static
    ports:
      - "8000:8000"
    environment:
      ENV: localdev
      AUTH: SAML_MOCK
      PORT: ${PORT:-8000}
      COMPRESSOR_ENABLED: "False"
    stdin_open: true
    tty: true
  node-bundler:
    build:
      context: .
      target: node-bundler
    volumes:
      - ./myuw:/app/myuw
      - statics-volume:/static
    command: bash -c "cd /app/ && npx webpack --watch"
volumes:
  statics-volume: