version: '3'

services:
  myuw:
    build: .
    container_name: myuw
    volumes:
      - ./myuw:/app/myuw
    ports:
      - "8000:8000"
    environment:
      ENV: localdev
      AUTH: SAML_MOCK
      PORT: ${PORT:-8000}
    stdin_open: true
    tty: true
